//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agm.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AgmEntities : DbContext
    {
        public AgmEntities()
            : base("name=AgmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistance> Asistance { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<TextMessage> TextMessage { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<userGroups_Result> userGroups(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<userGroups_Result>("userGroups", idParameter);
        }
    
        public virtual int spAddUserGroups(Nullable<int> userFk, Nullable<int> groupFk)
        {
            var userFkParameter = userFk.HasValue ?
                new ObjectParameter("userFk", userFk) :
                new ObjectParameter("userFk", typeof(int));
    
            var groupFkParameter = groupFk.HasValue ?
                new ObjectParameter("groupFk", groupFk) :
                new ObjectParameter("groupFk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddUserGroups", userFkParameter, groupFkParameter);
        }
    
        public virtual ObjectResult<spGroupsManager_Result> spGroupsManager(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGroupsManager_Result>("spGroupsManager", userIdParameter);
        }
    }
}
