//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agm.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextMessage
    {
        public int textId { get; set; }
        public string textOwner { get; set; }
        public string textContent { get; set; }
        public Nullable<int> groupFk { get; set; }
        public Nullable<System.DateTime> textDate { get; set; }
        public Nullable<int> userFk { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
